# Generated by Django 3.2.4 on 2021-06-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_subject_faculty'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='fac_group',
        ),
    ]
